version: '2'
services:
  jugtoulouse-app:
    image: jugtoulouse
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jugtoulouse-postgresql:5432/jugtoulouse
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  jugtoulouse-postgresql:
    extends:
      file: postgresql.yml
      service: jugtoulouse-postgresql
